### ISSUE TITLE
List of plants

### ISSUE THREAD

**Issue by M-Bohmann** [M-Bohmann/capstone-project#1]
## Value Proposition

**As a** user  
**I want to** view a list of insect friendly  balcony plants
**so that** i can decide which one i want to plant on my balcony
​

## Description

![Image](https://github.com/M-Bohmann/Tourio-App/assets/131541143/722e1df2-da4f-4eea-9e09-9848e8e99a29)

## Acceptance Criteria

- [ ] user can see a list of plants
- [ ] list scrolls vertically
- [ ] heading always visible
      ​

## Tasks

- [ ] create branch
- [ ] create dummy data
- [ ] create a heading
- [ ] create a card component
- [ ] add basic styling
      ​
