### ISSUE TITLE
Add own plant

### ISSUE THREAD

**Issue by M-Bohmann** [M-Bohmann/capstone-project#10]
## Value Proposition

**As a** user  
**I want to** add my own plants to my balcony list
**so that** I am not limited to the recommended plants
​

## Description

![Image](https://user-images.githubusercontent.com/131541143/250551054-a9347eae-d6ff-48f1-a494-cda637aaf646.png)

​

## Acceptance Criteria

- [x] user can see an add my own plant button
- [x] user gets redirected to a form, where they can fill out details of the plant
- [x] only the name is required
- [x] user can see a save button
- [x] if the user clicks the save button, they get redirected to the balcony plants site and they can see their plant in the list
      ​

## Tasks

- [x] add new branch US5-add-own-plant
- [x] add a new page for the form
- [x] create the form
- [x] name should be required
- [x] create heading
      ​

**Comment by Katemuya** [comment]
LGTM 🚀
