### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by M-Bohmann** [M-Bohmann/capstone-project#11]
## Value Proposition

**As a** user
**I want to** navigate through the pages
**so that** I can see my desired page
​

## Description

![Image](https://user-images.githubusercontent.com/131541143/250559799-aacaad19-4543-4d42-8303-c60ca6e8f6c5.png)

​

## Acceptance Criteria

- [ ] the user should see a navigation bar at the bottom
- [ ] the user is redirected to the clicked page
- [ ] the current page should be highlighted in the navigation bar
      ​

## Tasks

- [ ] create a branch US6-navbar
- [ ] create a navbar component
- [ ] add svgs to the navbar
- [ ] highlight the current page in the navbar
      ​

**Comment by Katemuya** [comment]
🚀🚀🚀
