### ISSUE TITLE
edit user plants

### ISSUE THREAD

**Issue by M-Bohmann** [M-Bohmann/capstone-project#12]
## Value Proposition

**As a** user
**I want to** edit my own plants  
**so that** I can update the information
​

## Description

![Image](https://user-images.githubusercontent.com/131541143/250798211-1de26c9e-1e02-4bea-8dcd-73bca291ccb4.png)

​

## Acceptance Criteria

- [ ] if the user clicks on their created plants, they can see a edit button at the bottom
- [ ] if the user clicks on the button, they can edit their previously entered data
- [ ] user can click on a cancel button to not save/discard his changes 
- [ ] user can click on the save button to save the changes
- [ ] user is redirected to the balcony plant planner when he clicks the save or cancel button
      ​

## Tasks

- [ ] create branch US7-edit-user-plants
- [ ] add edit button
- [ ] add cancel button 
      ​

**Comment by vokarl** [comment]
Nice user story! Perfectly understandable. 
Maybe it would be better to define the tasks more detailed e.g. link the cancel button to the homepage.
