### ISSUE TITLE
Search bar plants list

### ISSUE THREAD

**Issue by M-Bohmann** [M-Bohmann/capstone-project#14]
## Value Proposition

**As a** user
**I want to** search for a specific plant
**so that** the plant will be displayed and I can get more information
​

## Description

![Image](https://user-images.githubusercontent.com/131541143/250917932-90bdbc77-a7ad-45db-b780-ed58979ee5e5.png)

​

## Acceptance Criteria

- [ ] user can see a search bar with a search icon on the "Insektenfreunde für deinen Balkon" page
- [ ] user can search for a specific plant by only typing in the input field and it will be displayed
- [ ] user can only type a part of the name and all plants with this part will be displayed
- [ ] if the user clears the search bar all plants will be displayed again
      ​

## Tasks

- [ ] create branch US8-search-bar
- [ ] create the search bar component with an input field, a search svg, state
- [ ] add the search bar component to the "Insektenfreunde für deinen Balkon" page
      ​

**Comment by dimitriosxmi** [comment]
## LGTM great US! ⭐
