### ISSUE TITLE
US9 - MongoDB Atlas setup

### ISSUE THREAD

**Issue by M-Bohmann** [M-Bohmann/capstone-project#16]
## Value Proposition

**As a** user
**I want to** have my data accessible on all devices and browsers
**so that** I can easily switch between them without loosing my data
​

## Description

![Image](https://user-images.githubusercontent.com/131541143/251416856-50b61540-5076-4f8f-bd0c-f0aeb0e2019d.png)

​

## Acceptance Criteria

- [ ] app stays visually the same
- [ ] when adding/editing their plant, they can see the changes on all devices and browsers
      ​

## Tasks

- [ ] create a branch US9-db-setup
- [ ] setup MongoDB Atlas with dummy data
- [ ] establish a connection with MongoDB Atlas.
- [ ] change the code for MongoDB Atlas (schemes, C.R.U.D operations, etc.)

      ​

**Comment by MonaHer** [comment]
LGTM :)
