### ISSUE TITLE
US10 - add user plant picture

### ISSUE THREAD

**Issue by M-Bohmann** [M-Bohmann/capstone-project#17]
## Value Proposition

**As a** user
**I want to** upload a picture of my plant
**so that** I can see it in my balcony plants list
​

## Description

![Image](https://user-images.githubusercontent.com/131541143/251446626-04198452-2068-4b5e-8267-9219f97229bf.png)

​

## Acceptance Criteria

- [ ] user can see an upload button in the add own plant form
- [ ] user can choose their picture to upload
- [ ] after clicking save, the picture is saved with the other datas
- [ ] user should also see their picture on the plant details page
      ​

## Tasks

- [ ] create branch US10-user-plant-picture
- [ ] create picture upload field
- [ ] setup Cloudinary

      ​

**Comment by vaupunkt** [comment]
you could add a validation, that ensures that your upload will be successfull - https://www.triaxiomsecurity.com/file-upload-validation-techniques/

also: is this only about the upload function? otherwise maybe you could add, that some fields in your form are required. but i think your form was already part of another US? :)

**Comment by M-Bohmann** [comment]
Thanks for the review! 👍
Thanks for the validation tip, I'll keep this in mind when I come across this. 
Yes, the form was part of another US. 🙂
