### ISSUE TITLE
Plant details

### ISSUE THREAD

**Issue by M-Bohmann** [M-Bohmann/capstone-project#2]
## Value Proposition

**As a** user 
**I want to** click on a plant image
**so that** it shows me the details of this plant
​

## Description

![Image](https://github.com/M-Bohmann/Tourio-App/assets/131541143/0ff3fd28-6a66-4085-8dcb-6fe4aab8976c)

​

## Acceptance Criteria

- [ ] user can see the name of the plant, a image and characteristics of the plant
- [ ] user can navigate back to the list of plants via a button
      ​

## Tasks

- [ ] create branch
- [ ] create data
- [ ] create heading
- [ ] create a back button
- [ ] create plant details component
- [ ] implement dynamic routing
- [ ] add styling
      ​
