### ISSUE TITLE
US12-Styling

### ISSUE THREAD

**Issue by M-Bohmann** [M-Bohmann/capstone-project#20]
## Value Proposition

**As a** user
**I want to** see a styled app
**so that** I can enjoy it
​

## Description

Add styling to the app.
​

## Acceptance Criteria

- [ ] User can see an enjoyable styled app
      ​

## Tasks

- [ ] Create branch US12-styling
- [ ] Add styling to the entire app with styled components

**Comment by AliaksandraNovikava** [comment]
Hey @M-Bohmann 
I guess you can't really write a bunch of different acceptance criteria or tasks for this US.
LGTM👍
