### ISSUE TITLE
US11-Homepage

### ISSUE THREAD

**Issue by M-Bohmann** [M-Bohmann/capstone-project#23]
## Value Proposition

**As a** user
**I want to** get a short overview over the app and how to plan an insectfriendly balcony
**so that** I know all about it
​

## Description

![Image](https://user-images.githubusercontent.com/131541143/253948805-49c2b7cb-98cf-4edb-961f-5927b6934154.png)

​

## Acceptance Criteria

- [ ] user can see little information about the app
- [ ] user can see information about how the they can create an insect friendly balcony
      ​

## Tasks

- [ ] create branch US11-homepage
- [ ] add small info about the app
- [ ] add information about how the user can create an insect friendly balcony
      ​

**Comment by matschi3** [comment]
nice and clear US 🚀
